# This file was generated by GoReleaser. DO NOT EDIT.
cask "scout" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "4f4ca1e9ce6f475ca58d062df3f05d9ea9f5b1f7e8c5e4a3cb95920945c21531"
      url "https://github.com/tool7/scout/releases/download/v#{version}/scout_Darwin_x86_64.tar.gz",
        verified: "github.com/tool7/scout/"
    end
    on_arm do
      sha256 "fb07a3a6a707d652b38761896730a559936459cc90baa12f04bdea6115a167a5"
      url "https://github.com/tool7/scout/releases/download/v#{version}/scout_Darwin_arm64.tar.gz",
        verified: "github.com/tool7/scout/"
    end
  end

  on_linux do
    on_intel do
      sha256 "14222256bc31618ab9fa5f162c6ef4c1703365c2e3d43ded78eabf9698cab4b3"
      url "https://github.com/tool7/scout/releases/download/v#{version}/scout_Linux_x86_64.tar.gz",
        verified: "github.com/tool7/scout/"
    end
    on_arm do
      sha256 "aa9cf7b8e06e51fe9b38d4c5354ce3f4fdaafae33dadfe2049103ecf57ce52c6"
      url "https://github.com/tool7/scout/releases/download/v#{version}/scout_Linux_arm64.tar.gz",
        verified: "github.com/tool7/scout/"
    end
  end

  name "scout"
  desc "Local CLI for querying Git history, Jira tickets, and source code from configured projects."
  homepage "https://github.com/tool7/scout"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scout"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/scout"]
    end
  end

  # No zap stanza required

end
