# This file was generated by GoReleaser. DO NOT EDIT.
cask "scout" do
  version "1.0.3"

  on_macos do
    on_intel do
      sha256 "07c0ef488e1a33e3beeaff3ff7b468d2190f5cc987487da881289101305bf2e1"
      url "https://github.com/tool7/scout/releases/download/v#{version}/scout_Darwin_x86_64.tar.gz",
        verified: "github.com/tool7/scout/"
    end
    on_arm do
      sha256 "cf4f11f84b8a620a7c8a1820588c8289ae87dace7d7f04a0eebb08088f39867c"
      url "https://github.com/tool7/scout/releases/download/v#{version}/scout_Darwin_arm64.tar.gz",
        verified: "github.com/tool7/scout/"
    end
  end

  on_linux do
    on_intel do
      sha256 "21d292e45ba397a04360f641dafafff37fb96e3079af812cb4258c5aa05331c4"
      url "https://github.com/tool7/scout/releases/download/v#{version}/scout_Linux_x86_64.tar.gz",
        verified: "github.com/tool7/scout/"
    end
    on_arm do
      sha256 "3b570f27fd8b669ec23da3dc5ce088e0998810db09460cc0a4c35d42b3d7f30e"
      url "https://github.com/tool7/scout/releases/download/v#{version}/scout_Linux_arm64.tar.gz",
        verified: "github.com/tool7/scout/"
    end
  end

  name "scout"
  desc "Local CLI for querying Git history, Jira tickets, and source code from configured projects."
  homepage "https://github.com/tool7/scout"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scout"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/scout"]
    end
  end

  # No zap stanza required

end
