# This file was generated by GoReleaser. DO NOT EDIT.
cask "scout" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "9a96d6db75e5a41fa5b8485e645a563064c8be2ac77678ba89e0ede55ef0c9ec"
      url "https://github.com/tool7/scout/releases/download/v#{version}/scout_Darwin_x86_64.tar.gz",
        verified: "github.com/tool7/scout/"
    end
    on_arm do
      sha256 "5963af69e3f58bc519351e3f658cd592c758847b242d19e6a071d0a4ba2087ab"
      url "https://github.com/tool7/scout/releases/download/v#{version}/scout_Darwin_arm64.tar.gz",
        verified: "github.com/tool7/scout/"
    end
  end

  on_linux do
    on_intel do
      sha256 "89dbf6f1e8eca59d0590ac717347af4ccbf5c2ef6da4cc3b00bcf1bcb3d1d116"
      url "https://github.com/tool7/scout/releases/download/v#{version}/scout_Linux_x86_64.tar.gz",
        verified: "github.com/tool7/scout/"
    end
    on_arm do
      sha256 "db90fb68023b2ee6ec223fd0473fc1b1b82e172c9339c0a4f43ab68885ea6695"
      url "https://github.com/tool7/scout/releases/download/v#{version}/scout_Linux_arm64.tar.gz",
        verified: "github.com/tool7/scout/"
    end
  end

  name "scout"
  desc "Local CLI for querying Git history, Jira tickets, and source code from configured projects."
  homepage "https://github.com/tool7/scout"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scout"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/scout"]
    end
  end

  # No zap stanza required

end
